### ISSUE TITLE
vias : not working

### ISSUE THREAD

**Issue by trou** [davidcarne/pcbre#3]
Hello,
how that #2 is fixed, I can add information to my layers but it seems *vias* don't work. Nothing shows up when I try to add one.

Maybe I'm missing something regarding layers ?

**Comment by davidcarne** [comment]
Ok - we've resolved this on IRC. Basically, the real error is #6.

For anyone else trying to use vias, the sequence of operations is:

- Go to the stackup dialog, right click, add a viapair (need at least two layers)
- long-click on the Via icon, then select the created viapair
- Click on the window to add vias
