### ISSUE TITLE
shaderprogram.check_validate() causes exception on failure on OS X

### ISSUE THREAD

**Issue by balr0g** [davidcarne/pcbre#8]
The call to GLS.compileProgram() in PyOpenGL (called from https://github.com/davidcarne/pcbre/blob/master/pysrc/pcbre/ui/gl/shadercache.py#L69) in turn calls program.check_validate(). On OS X, this throws an exception if the OpenGL state isn't completely set up.

The proposed fix was to rework the code in https://github.com/davidcarne/pcbre/blob/master/pysrc/pcbre/ui/gl/shader.py to correctly use EnhShaderProgram. My temporary fix was to use the compileProgram function from that module, and wrapping the call to check_validate() in a try/except block.

**Comment by davidcarne** [comment]
Fixed in 7cc3df5c27209e7da878338659a87b8aa39f6a04
